%YAML:1.0
####################### General Parameters ########################

imu: 0 #enable imu or not
num_of_cam: 2

only_imgprocess: 0  #for debug
only_frontend: 0  #for debug

dataset_type: "custom" #support:kitti,viode
slam_type: "raw" #SLAM mode,optional:raw,naive,dynamic

use_line: 0 #line feature

basic_dir: "/home/chen/ws/dynamic_ws/src/dynamic_vins/"

plane_constraint: 1 #是否使用平面约束
undistort_input: 1 #是否对输入进行矫正
show_input: 0 #显示输入图像

####################### Camera Parameters ########################
cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"

image_width: 1280
image_height: 800

######################### Extrinsic ###########################
#Whether to estimate the extrinsic between the camera and IMU,
#0 means that there are fixed extrinsic, and external parameters are not estimated;
#1 means estimated extrinsic with initial value
#2 means estimated extrinsic, but no initial initial value
estimate_extrinsic: 0

#body_T_cam0: !!opencv-matrix
#  rows: 4
#  cols: 4
#  dt: d
#  data: [0.9980375839238246, 0.0012738811789833162, 0.06260477858948245, 0.0559500190917525,
#         0.0017832425342426393, 0.9988093229582538, -0.048751988859330644, -0.022218317938504973,
#         -0.0625923407579582, 0.04876795667667515, 0.9968469718467439, -0.06608421910045355,
#         0.0, 0.0, 0.0, 1.0]

#body_T_cam1: !!opencv-matrix
#  rows: 4
#  cols: 4
#  dt: d
#  data: [0.999949723776607, 0.003553356413655465, 0.009376757290521136, -0.02110786757132524,
#         -0.003068549046900963, 0.9986826628266313, -0.051220337525793726, -0.021640808301362585,
#         -0.009546409054433552, 0.051188989321015156, 0.9986433564824125, -0.06301244925948868,
#         0.0, 0.0, 0.0, 1.0]


body_T_cam0: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [1.0, 0.0, 0.0, 0.0,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]

body_T_cam1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [1.0, 0.0, 0.0, 0.08,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]

####################### ROS Topic ########################

##### 发布的话题
vins_vio_topic: "/dynamic_vins/odometry"
vins_keyframe_pose_topic: "/dynamic_vins/keyframe_pose"
vins_extrinsic_topic: "/dynamic_vins/extrinsic"
vins_keyframe_point_topic: "/dynamic_vins/keyframe_point"
vins_margin_cloud_topic: "/dynamic_vins/margin_cloud"

####################### Frontend Parameters ########################

max_cnt: 250            # max feature number in feature tracking
min_dist: 25            # min distance between two features
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy


min_dynamic_dist: 4 #检测动态特征点时每个点之间的最小距离
max_dynamic_cnt: 50 #前端中每个动态物体上最多同时跟踪的特征数量

use_mask_morphology: 1 #是否对输入mask进行形态学运算
mask_morphology_size: 20

####################### VIO Parameters ########################

#optimization parameters
max_solver_time: 0.08  # max solver itration time (s), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 15 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.025772789820144627          # accelerometer measurement noise standard deviation. #0.2   0.04
acc_w: 0.00022385207686569393         # accelerometer bias random work noise standard deviation.  #0.02
gyr_n: 0.0018298682132947672         # gyroscope measurement noise standard deviation.     #0.05  0.004
gyr_w: 1.82951645725973e-05       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0   # online estimate time offset between camera and imu
#td: -0.034158789501110766  # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
td: 0

INIT_DEPTH: 5.0
BIAS_ACC_THRESHOLD: 0.1
BIAS_GYR_THRESHOLD: 0.1

#######################  Log Parameters ########################
estimator_log_level: "debug"
estimator_log_flush: "info"
feature_tracker_log_level: "debug"
feature_tracker_log_flush: "info"
segmentor_log_level: "debug"
segmentor_log_flush: "info"
log_output_path: "data/log/"

#是否输出每一帧的每个路标点和位姿的信息,用于debug
print_detail: 0

####################### Visualization Parameters ########################
visual_inst_duration: 200  #duration of marker display

pub_groundtruth_box: 0
pub_predict_box: 0
pub_object_axis: 1
pub_object_trajectory: 1

show_track: 1           #可视化相机

####################### Dataloader Parameters ########################
use_dataloader: 0 #read image for disk,not from ros
image0_topic: "/mynteye/left_rect/image_rect"
image1_topic: "/mynteye/right_rect/image_rect"

imu_topic: "/mynteye/imu/data_raw"

######################### Bounding box ########################
use_det3d: 0

####################### Flow Parameters ########################
use_dense_flow: 0 #是否使用稠密光流