%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1242
image_height: 375
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 7.215377e+02
   fy: 7.215377e+02
   cx: 6.095593e+02
   cy: 1.728540e+02