%YAML:1.0

#common parameters
imu: 0
num_of_cam: 2

dataset_type: "kitti"

#kitti
imu_topic: "/kitti/oxts/imu"
#image0_topic: "/kitti/camera_color_left/image_raw"
#image1_topic: "/kitti/camera_color_right/image_raw"
image0_topic: "/camera/left/image_raw"
image1_topic: "/camera/right/image_raw"

cam0_calib: "cam_09_30.yaml"
cam1_calib: "cam_09_30.yaml"
image_width: 1226
image_height: 370


# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1, 0, 0, 0,
          0, 1, 0, 0,
          0, 0, 1, 0,
          0, 0, 0, 1]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1, 0, 0, 0.537150653267924,
          0, 1, 0, 0,
          0, 0, 1, 0,
          0, 0, 0, 1]


#feature traker paprameters
max_cnt: 250            # max feature number in feature tracking
min_dist: 25            # min distance between two features
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.08  # max solver itration time (s), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 15 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 1.0e-4       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

INIT_DEPTH: 5.0
BIAS_ACC_THRESHOLD: 0.1
BIAS_GYR_THRESHOLD: 0.1

vins_vio_topic: "/dynamic_vins/odometry"
vins_keyframe_pose_topic: "/dynamic_vins/keyframe_pose"
vins_extrinsic_topic: "/dynamic_vins/extrinsic"
vins_keyframe_point_topic: "/dynamic_vins/keyframe_point"
vins_margin_cloud_topic: "/dynamic_vins/margin_cloud"

output_path: "/home/chen/ws/dynamic_ws/output/"

#SOLO
SOLO_NMS_PRE: 500
SOLO_MAX_PER_IMG: 100
SOLO_NMS_KERNEL: "gaussian"
#SOLO_NMS_SIGMA=2.0
SOLO_NMS_SIGMA: 2.0
SOLO_SCORE_THR: 0.1
SOLO_MASK_THR: 0.5
SOLO_UPDATE_THR: 0.2

tracking_max_age: 30
tracking_n_init: 3

min_dynamic_dist: 10
max_dynamic_cnt: 50

#物体可视化的持续时间
visual_inst_duration: 120

basic_dir: "/home/chen/ws/dynamic_ws/src/dynamic_vins/"

extractor_model_path: "weights/deepsort/ckpt.bin"

#log
estimator_log_path: "output/estimator_log.txt"
estimator_log_level: "debug"
estimator_log_flush: "debug"
feature_tracker_log_path: "output/tracker_log.txt"
feature_tracker_log_level: "debug"
feature_tracker_log_flush: "debug"
segmentor_log_path: "output/segmentor_log.txt"
segmentor_log_level: "debug"
segmentor_log_flush: "debug"

fnet_onnx_path: "weights/raft/kitti_fnet.onnx"
fnet_tensorrt_path: "weights/raft/kitti_fnet.bin"
cnet_onnx_path: "weights/raft/kitti_cnet.onnx"
cnet_tensorrt_path: "weights/raft/kitti_cnet.bin"
update_onnx_path: "weights/raft/kitti_update.onnx"
update_tensorrt_path: "weights/raft/kitti_update.bin"

solo_onnx_path: "weights/solo/SOLOv2_light_R34_1152x384_cuda102.onnx"
solo_serialize_path: "weights/solo/tensorrt_model_1152x384.bin"

#0表示raw,1表示naive,2表示dynamic
slam_type: 2
