%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 720
distortion_parameters:
   k1: -0.0369
   k2: 0.0595
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 1001.7
   fy: 1000.5
   cx: 626.5953
   cy: 517.4959

