%YAML:1.0
####################### 通用参数 ########################

imu: 0 #是否使用IMU
num_of_cam: 2 #相机的数量

only_imgprocess: 0  #是否仅仅图像处理部分
only_frontend: 0  #是否仅仅启动前端

dataset_type: "kitti" #数据集类型,支持kitti,viode

slam_type: "dynamic" #SLAM模式,可选:raw,naive,dynamic

#是否估计相机和IMU之间的外参数,
# 0表示已有固定的外参,不估计外参;
# 1表示估计外参,且有初始外参
# 2表示估计外参,但无初始外参
estimate_extrinsic: 0

visual_inst_duration: 120  #物体可视化的持续时间

basic_dir: "/home/chen/ws/dynamic_ws/src/dynamic_vins/"



#直接读取图像
dataset_sequence: "0004"

kitti_calib_path: "/home/chen/datasets/kitti/tracking/data_tracking_calib/training/calib/0002.txt" #相机内参

det3d_preprocess_path: "/home/chen/datasets/kitti/tracking/det3d_02/training/image_02/" #预处理的3D框
det2d_preprocess_path: "/home/chen/datasets/kitti/tracking/det2d_02/training/image_02/" #预处理的2D框

use_dataloader: 1 #是否直接读取图像
#以下选项当use_dataloader=1时有效
image_dataset_period: 100 #读取的时间周期,毫秒
image_dataset_left: "/home/chen/datasets/kitti/tracking/data_tracking_image_2/training/image_02/"
image_dataset_right: "/home/chen/datasets/kitti/tracking/data_tracking_image_3/training/image_03/"

####################### 相机参数 ########################

#kitti tracking
image_width: 1242
image_height: 375

######################### 预处理的3D包围框 ########################
det3d_score_threshold: 0.15
use_offline_det3d: 1
use_offline_det2d: 1

####################### 光流的参数 ########################

use_dense_flow: 0 #是否使用稠密光流
use_background_flow: 0 #背景特征点是否使用稠密光流
use_offline_flow: 1 #是否使用预计算的光流
flow_offline_path: "/home/chen/Datasets/kitti/tracking_flow/image_02/" #预计算的光流


fnet_onnx_path: "weights/raft/kitti_fnet.onnx"
fnet_tensorrt_path: "weights/raft/kitti_fnet.bin"
cnet_onnx_path: "weights/raft/kitti_cnet.onnx"
cnet_tensorrt_path: "weights/raft/kitti_cnet.bin"
update_onnx_path: "weights/raft/kitti_update.onnx"
update_tensorrt_path: "weights/raft/kitti_update.bin"

####################### 订阅和发布的ROS话题名 ########################

##### 订阅的话题, 若use_dataloader==1,则忽略
#kitti
image0_topic: "/kitti_pub/left"
image1_topic: "/kitti_pub/right"


##### 发布的话题
vins_vio_topic: "/dynamic_vins/odometry"
vins_keyframe_pose_topic: "/dynamic_vins/keyframe_pose"
vins_extrinsic_topic: "/dynamic_vins/extrinsic"
vins_keyframe_point_topic: "/dynamic_vins/keyframe_point"
vins_margin_cloud_topic: "/dynamic_vins/margin_cloud"


####################### 前端的参数 ########################

max_cnt: 250            # max feature number in feature tracking
min_dist: 25            # min distance between two features
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

min_dynamic_dist: 10 #检测动态特征点时每个点之间的最小距离
max_dynamic_cnt: 50 #前端中每个动态物体上最多同时跟踪的特征数量

####################### VIO的参数 ########################

#optimization parameters
max_solver_time: 0.08  # max solver itration time (s), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 15 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 1.0e-4       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

INIT_DEPTH: 5.0
BIAS_ACC_THRESHOLD: 0.1
BIAS_GYR_THRESHOLD: 0.1



####################### 实例分割SOLO的参数 ########################

SOLO_NMS_PRE: 500
SOLO_MAX_PER_IMG: 100
SOLO_NMS_KERNEL: "gaussian"
#SOLO_NMS_SIGMA=2.0
SOLO_NMS_SIGMA: 2.0
SOLO_SCORE_THR: 0.1
SOLO_MASK_THR: 0.5
SOLO_UPDATE_THR: 0.2

solo_onnx_path: "weights/solo/SOLOv2_light_R34_1152x384_cuda102.onnx"
solo_serialize_path: "weights/solo/tensorrt_model_1152x384.bin"

warn_up_image: "/home/chen/ws/vio_ws/src/dynamic_vins/config/kitti.png"

####################### MOT的参数 ########################
tracking_max_age: 30
tracking_n_init: 3

extractor_model_path: "weights/deepsort/ckpt.bin"



####################### log的参数 ########################
estimator_log_path: "data/output/vio_log.txt"
estimator_log_level: "debug"
estimator_log_flush: "debug"
feature_tracker_log_path: "data/output/frontend_log.txt"
feature_tracker_log_level: "debug"
feature_tracker_log_flush: "debug"
segmentor_log_path: "data/output/img_process_log.txt"
segmentor_log_level: "debug"
segmentor_log_flush: "debug"

print_detail: 1

####################### 动态物体参数 ########################
instance_init_min_num: 4
instance_static_err_threshold: 10.0





