%YAML:1.0
####################### General Parameters ########################

imu: 0 #enable imu or not
num_of_cam: 2

only_imgprocess: 0  #for debug
only_frontend: 0  #for debug

dataset_type: "kitti" #support:kitti,viode
slam_type: "dynamic" #SLAM mode,optional:raw,naive,dynamic

use_line: 0 #line feature
undistort_input: 0 #是否对输入进行矫正

basic_dir: "/home/chen/ws/dynamic_ws/src/dynamic_vins/"

plane_constraint: 0 #是否使用平面约束


####################### Camera Parameters ########################

kitti_calib_path: "/home/chen/datasets/kitti/tracking/data_tracking_calib/training/calib/" #相机内参

#kitti tracking seq:18
#image_width: 1238
#image_height: 374

#kitti tracking seq:0-10
image_width: 1242
image_height: 375

######################### Extrinsic ###########################
#Whether to estimate the extrinsic between the camera and IMU,
#0 means that there are fixed extrinsic, and external parameters are not estimated;
#1 means estimated extrinsic with initial value
#2 means estimated extrinsic, but no initial initial value
estimate_extrinsic: 0

####################### ROS Topic ########################

##### 发布的话题
vins_vio_topic: "/dynamic_vins/odometry"
vins_keyframe_pose_topic: "/dynamic_vins/keyframe_pose"
vins_extrinsic_topic: "/dynamic_vins/extrinsic"
vins_keyframe_point_topic: "/dynamic_vins/keyframe_point"
vins_margin_cloud_topic: "/dynamic_vins/margin_cloud"


####################### Frontend Parameters ########################

max_cnt: 250            # max feature number in feature tracking
min_dist: 25            # min distance between two features
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

min_dynamic_dist: 4 #检测动态特征点时每个点之间的最小距离
max_dynamic_cnt: 50 #前端中每个动态物体上最多同时跟踪的特征数量

use_mask_morphology: 1 #是否对输入mask进行形态学运算
mask_morphology_size: 20

####################### VIO Parameters ########################

#optimization parameters
max_solver_time: 0.08  # max solver itration time (s), to guarantee real time
max_num_iterations: 10   # max solver itrations, to guarantee real time
keyframe_parallax: 15 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 1.0e-4       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

INIT_DEPTH: 5.0
BIAS_ACC_THRESHOLD: 0.1
BIAS_GYR_THRESHOLD: 0.1


####################### Log Parameters ########################
estimator_log_level: "debug"
estimator_log_flush: "debug"
feature_tracker_log_level: "debug"
feature_tracker_log_flush: "debug"
segmentor_log_level: "info"
segmentor_log_flush: "info"
log_output_path: "data/log/"

#for debug
print_detail: 1

#for debug，输出某些id的物体的位姿
print_inst_ids: [1,4,5]

####################### Visualization Parameters ########################
visual_inst_duration: 1000  #duration of marker display

pub_groundtruth_box: 0 #可视化物体的GT框

#当pub_groundtruth_box==1时，设置该路径
object_groundtruth_path: "/home/chen/datasets/kitti/tracking/data_tracking_label_2/training/label_02/"

pub_predict_box: 0 #可视化3D检测框

pub_object_axis: 1
pub_object_trajectory: 1

show_input: 1

####################### Dynamic Parameters ########################

instance_init_min_num: 4
instance_static_err_threshold: 10.0


stereo_preprocess_path: "/home/chen/datasets/kitti/tracking/stereo/training/"

######################### Bounding box ########################
use_det3d: 1
det3d_score_threshold: 0.15
use_offline_det3d: 1
det3d_preprocess_path: "/home/chen/datasets/kitti/tracking/det3d_02/training/image_02_pgd/" #预处理的3D框


use_offline_det2d: 1
det2d_preprocess_path: "/home/chen/datasets/kitti/tracking/det2d_02/training/image_02/" #预处理的2D框


box2d_min_height: 0 #至少高40pixel才会被处理

####################### MOT Parameters ########################
tracking_max_age: 5
tracking_n_init: 3

extractor_model_path: "weights/deepsort/ckpt.bin" #外观模型

####################### Dataloader Parameters ########################
use_dataloader: 1 #read image for disk,not from ros
#以下选项当use_dataloader=1时有效
image_dataset_period: 400 #
image_dataset_left: "/home/chen/datasets/kitti/tracking/data_tracking_image_2/training/image_02/"
image_dataset_right: "/home/chen/datasets/kitti/tracking/data_tracking_image_3/training/image_03/"

####################### Flow Parameters ########################

use_dense_flow: 0 #是否使用稠密光流

