%YAML:1.0
####################### General Parameters ########################

imu: 1 #enable imu or not
num_of_cam: 2

only_imgprocess: 0  #for debug
only_frontend: 1  #for debug

dataset_type: "viode" #support:kitti,viode
slam_type: "raw" #SLAM mode,optional:raw,naive,dynamic

use_line: 1 #line feature


basic_dir: "/home/chen/ws/dynamic_ws/src/dynamic_vins/"

#the input sequence id
dataset_sequence: "parking_lot_0_none"

plane_constraint: 0 #是否使用平面约束


####################### Camera Parameters ########################

image_width: 752
image_height: 480

cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"


######################### Extrinsic ###########################
#Whether to estimate the extrinsic between the camera and IMU,
#0 means that there are fixed extrinsic, and external parameters are not estimated;
#1 means estimated extrinsic with initial value
#2 means estimated extrinsic, but no initial initial value
estimate_extrinsic: 0

body_T_cam0: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.0, 0.0, 1.0, 0.0,
         1.0, 0.0, 0.0, 0.0,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 0.0, 1.0]

body_T_cam1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.0, 0.0, 1.0, 0.0,
         1.0, 0.0, 0.0, 0.05,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 0.0, 1.0]


####################### ROS Topic ########################
##### 订阅的话题, 若use_dataloader==1,则忽略
image0_topic: "/cam0/image_raw"
image1_topic: "/cam1/image_raw"

image0_segmentation_topic: "/cam0/segmentation"
image1_segmentation_topic: "/cam1/segmentation"

imu_topic: "/imu0"

##### 发布的话题
vins_vio_topic: "/dynamic_vins/odometry"
vins_keyframe_pose_topic: "/dynamic_vins/keyframe_pose"
vins_extrinsic_topic: "/dynamic_vins/extrinsic"
vins_keyframe_point_topic: "/dynamic_vins/keyframe_point"
vins_margin_cloud_topic: "/dynamic_vins/margin_cloud"


####################### Frontend Parameters ########################

max_cnt: 160            # max feature number in feature tracking
min_dist: 20            # min distance between two features
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

min_dynamic_dist: 5 #检测动态特征点时每个点之间的最小距离
max_dynamic_cnt: 50 #前端中每个动态物体上最多同时跟踪的特征数量


use_mask_morphology: 1 #是否对输入mask进行形态学运算
mask_morphology_size: 5

####################### VIO Parameters ########################

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.2          # accelerometer measurement noise standard deviation.
gyr_n: 0.05         # gyroscope measurement noise standard deviation.
acc_w: 0.02         # accelerometer bias random work noise standard deviation.
gyr_w: 4.0e-5       # gyroscope bias random work noise standard deviation.
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

INIT_DEPTH: 5.0
BIAS_ACC_THRESHOLD: 0.1
BIAS_GYR_THRESHOLD: 0.1


#######################  Log Parameters ########################
estimator_log_level: "info"
estimator_log_flush: "info"
feature_tracker_log_level: "info"
feature_tracker_log_flush: "info"
segmentor_log_level: "info"
segmentor_log_flush: "info"
log_output_path: "data/log/"

#是否输出每一帧的每个路标点和位姿的信息,用于debug
print_detail: 0

####################### Visualization Parameters ########################
visual_inst_duration: 120  #duration of marker display

pub_groundtruth_box: 0
pub_predict_box: 0
pub_object_axis: 1
pub_object_trajectory: 1

####################### Dynamic Parameters ########################
instance_init_min_num: 4
instance_static_err_threshold: 10.0

######################### Bounding box ########################
use_det3d: 0

####################### Flow Parameters ########################
use_dense_flow: 0 #是否使用稠密光流
#use_background_flow: 0 #背景特征点是否使用稠密光流
#use_preprocess_flow: 0 #是否使用预计算的光流
#flow_preprocess_path: "/home/chen/datasets/kitti/tracking/flow_02/training/image_02/0007/"
#flow_preprocess_path: "/home/chen/Datasets/kitti/tracking_flow/image_02/0007/"

#fnet_onnx_path: "weights/raft/kitti_fnet.onnx"
#fnet_tensorrt_path: "weights/raft/kitti_fnet.bin"
#cnet_onnx_path: "weights/raft/kitti_cnet.onnx"
#cnet_tensorrt_path: "weights/raft/kitti_cnet.bin"
#update_onnx_path: "weights/raft/kitti_update.onnx"
#update_tensorrt_path: "weights/raft/kitti_update.bin"


####################### VIODE parameters ########################
rgb_to_label_file: "config/viode/VIODE-master/segmentation/rgb_ids.txt"
dynamic_label_id: [241,242,243,244,245,246,247,248,249,250,251,254,255]

